In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
import pickle
import numpy as np
from tensorflow.keras import layers
import os


In [3]:
with open('data.txt','r',encoding='utf-8') as f:
    data = f.read()

In [4]:
data

'Dr. A.P.J. Abdul Kalam, born Avul Pakir Jainulabdeen Abdul Kalam, embarked on a remarkable journey from humble beginnings to become one of India\'s most revered figures. His life story is a testament to perseverance, dedication, and an unwavering commitment to national development.\n\nHere\'s a detailed look at his inspiring journey:\n\n### Early Life and Education (1931-1960)\n\n* **Birth and Childhood:** Avul Pakir Jainulabdeen Abdul Kalam was born on October 15, 1931, in Rameswaram, Tamil Nadu, into a Tamil Muslim family. His father, Jainulabdeen, was a boat owner and imam, and his mother, Ashiamma, was a housewife. Despite his ancestors being wealthy traders, the family faced financial hardship during his childhood. To support his family, young Kalam sold newspapers.\n* **Early Education:** He attended Schwartz Higher Secondary School in Ramanathapuram, where he was described as a bright and hardworking student with a strong desire to learn, especially mathematics.\n* **Higher Edu

In [5]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=10000, oov_token="<OOV>")



In [6]:
tokenizer.fit_on_texts([data])

In [7]:
tokenizer

In [8]:
tokenizer.word_index

{'<OOV>': 1,
 'a': 2,
 'the': 3,
 'to': 4,
 'and': 5,
 'his': 6,
 'he': 7,
 'in': 8,
 'of': 9,
 'india': 10,
 'missile': 11,
 'was': 12,
 'for': 13,
 'kalam': 14,
 'from': 15,
 'national': 16,
 'development': 17,
 'as': 18,
 'on': 19,
 "india's": 20,
 'an': 21,
 'abdul': 22,
 'at': 23,
 'indian': 24,
 'dr': 25,
 'with': 26,
 "kalam's": 27,
 'drdo': 28,
 'president': 29,
 'journey': 30,
 'inspiring': 31,
 'education': 32,
 'institute': 33,
 'project': 34,
 'scientific': 35,
 '2002': 36,
 'research': 37,
 'space': 38,
 'july': 39,
 'range': 40,
 'surface': 41,
 '2007': 42,
 'students': 43,
 'vision': 44,
 '2020': 45,
 'p': 46,
 'j': 47,
 'jainulabdeen': 48,
 'become': 49,
 'is': 50,
 'early': 51,
 'into': 52,
 'family': 53,
 'during': 54,
 'support': 55,
 'by': 56,
 'technology': 57,
 'successfully': 58,
 'air': 59,
 'defence': 60,
 'isro': 61,
 '1969': 62,
 '1982': 63,
 'first': 64,
 'satellite': 65,
 'man': 66,
 'including': 67,
 'ballistic': 68,
 'ii': 69,
 'nuclear': 70,
 'tests': 71

In [9]:
sequence=(tokenizer.texts_to_sequences([data])[0])

In [10]:
sequence

[25,
 2,
 46,
 47,
 22,
 14,
 80,
 81,
 82,
 48,
 22,
 14,
 159,
 19,
 2,
 160,
 30,
 15,
 161,
 162,
 4,
 49,
 163,
 9,
 20,
 83,
 164,
 165,
 6,
 84,
 166,
 50,
 2,
 167,
 4,
 168,
 85,
 5,
 21,
 169,
 170,
 4,
 16,
 17,
 171,
 2,
 172,
 173,
 23,
 6,
 31,
 30,
 51,
 84,
 5,
 32,
 86,
 87,
 174,
 5,
 88,
 81,
 82,
 48,
 22,
 14,
 12,
 80,
 19,
 175,
 176,
 86,
 8,
 89,
 90,
 177,
 52,
 2,
 90,
 178,
 53,
 6,
 179,
 48,
 12,
 2,
 180,
 181,
 5,
 182,
 5,
 6,
 183,
 184,
 12,
 2,
 185,
 91,
 6,
 186,
 187,
 188,
 189,
 3,
 53,
 92,
 190,
 191,
 54,
 6,
 88,
 4,
 55,
 6,
 53,
 192,
 14,
 193,
 194,
 51,
 32,
 7,
 195,
 196,
 93,
 197,
 198,
 8,
 199,
 94,
 7,
 12,
 200,
 18,
 2,
 201,
 5,
 202,
 203,
 26,
 2,
 204,
 205,
 4,
 206,
 95,
 207,
 93,
 32,
 7,
 208,
 8,
 209,
 15,
 210,
 211,
 212,
 213,
 8,
 214,
 215,
 56,
 6,
 96,
 7,
 216,
 4,
 97,
 217,
 218,
 8,
 219,
 4,
 220,
 221,
 222,
 23,
 3,
 97,
 33,
 9,
 57,
 98,
 54,
 2,
 223,
 224,
 34,
 7,
 92,
 2,
 225,
 15,
 6,
 226,
 99,

In [11]:
len(sequence)

1080

In [12]:
##save the tokenizer
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [13]:
def create_dataset(sequence, window_size=100):
    input,labels=[],[]
    for i in range(len(sequence)-window_size):
        input.append(sequence[i:i+window_size])
        labels.append(sequence[i+1:i+window_size+1])
    return np.array(input), np.array(labels)

In [14]:
X_data,y_data=create_dataset(sequence)

In [15]:
X_data.shape

(980, 100)

In [16]:
y_data.shape

(980, 100)

In [17]:
X_data

array([[ 25,   2,  46, ...,  91,   6, 186],
       [  2,  46,  47, ...,   6, 186, 187],
       [ 46,  47,  22, ..., 186, 187, 188],
       ...,
       [ 45, 464, 465, ..., 508,  16, 509],
       [464, 465, 466, ...,  16, 509,   5],
       [465, 466,  79, ..., 509,   5, 510]])

In [18]:
y_data

array([[  2,  46,  47, ...,   6, 186, 187],
       [ 46,  47,  22, ..., 186, 187, 188],
       [ 47,  22,  14, ..., 187, 188, 189],
       ...,
       [464, 465, 466, ...,  16, 509,   5],
       [465, 466,  79, ..., 509,   5, 510],
       [466,  79,   5, ...,   5, 510, 140]])

In [19]:
X_data[0]

array([ 25,   2,  46,  47,  22,  14,  80,  81,  82,  48,  22,  14, 159,
        19,   2, 160,  30,  15, 161, 162,   4,  49, 163,   9,  20,  83,
       164, 165,   6,  84, 166,  50,   2, 167,   4, 168,  85,   5,  21,
       169, 170,   4,  16,  17, 171,   2, 172, 173,  23,   6,  31,  30,
        51,  84,   5,  32,  86,  87, 174,   5,  88,  81,  82,  48,  22,
        14,  12,  80,  19, 175, 176,  86,   8,  89,  90, 177,  52,   2,
        90, 178,  53,   6, 179,  48,  12,   2, 180, 181,   5, 182,   5,
         6, 183, 184,  12,   2, 185,  91,   6, 186])

In [20]:
y_data[0]

array([  2,  46,  47,  22,  14,  80,  81,  82,  48,  22,  14, 159,  19,
         2, 160,  30,  15, 161, 162,   4,  49, 163,   9,  20,  83, 164,
       165,   6,  84, 166,  50,   2, 167,   4, 168,  85,   5,  21, 169,
       170,   4,  16,  17, 171,   2, 172, 173,  23,   6,  31,  30,  51,
        84,   5,  32,  86,  87, 174,   5,  88,  81,  82,  48,  22,  14,
        12,  80,  19, 175, 176,  86,   8,  89,  90, 177,  52,   2,  90,
       178,  53,   6, 179,  48,  12,   2, 180, 181,   5, 182,   5,   6,
       183, 184,  12,   2, 185,  91,   6, 186, 187])

In [21]:
class PositionalEncoding(layers.Layer):
    def __init__(self, d_model, max_len):
        super().__init__()
        pos=np.arange(max_len)[:, np.newaxis]
        i=np.arange(d_model)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i // 2)) / np.float32(d_model)) 
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        self.pos_encoding = tf.cast(angle_rads[np.newaxis, ...], dtype=tf.float32)

    def call(self,x):
        return x + self.pos_encoding[:, :tf.shape(x)[1], :]


In [22]:
from tensorflow.keras import layers
from tensorflow.keras.models import Model

def transformer_block(embed_dim, num_heads, ff_dim, dropout=0.1):
    inputs = layers.Input(shape=(None, embed_dim))
    
    # Multi-head self-attention
    attn_output = layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)(inputs, inputs)
    attn_output = layers.Dropout(dropout)(attn_output)
    out1 = layers.LayerNormalization(epsilon=1e-6)(inputs + attn_output)
    
    # Feed-forward network
    ffn = tf.keras.Sequential([
        layers.Dense(ff_dim, activation='relu'),
        layers.Dense(embed_dim)
    ])
    ffn_output = ffn(out1)
    ffn_output = layers.Dropout(dropout)(ffn_output)
    
    # Output after second residual connection + normalization
    out2 = layers.LayerNormalization(epsilon=1e-6)(out1 + ffn_output)
    
    return Model(inputs=inputs, outputs=out2)



In [23]:
vocab_size=10000
max_seq_length=100
num_heads=16
ff_dim=512
num_layers=4
batch_size=64
epochs=10
embed_dim=100

def build_gpt_model():
    input=layers.Input(shape=(max_seq_length, ))
    x=layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)(input)
    
    x=PositionalEncoding(max_seq_length,embed_dim)(x)

    for _ in range(num_layers):
        x=transformer_block(embed_dim=embed_dim, num_heads=num_heads, ff_dim=ff_dim)(x)
    output=layers.Dense(vocab_size, activation='softmax')(x)
    return tf.keras.Model(inputs=input, outputs=output)    

In [24]:
model=build_gpt_model()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_data, y_data, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 73s 5s/step - accuracy: 0.0076 - loss: 8.3369 - val_accuracy: 0.0129 - val_loss: 8.0107
Epoch 2/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 52s 4s/step - accuracy: 0.0262 - loss: 6.6237 - val_accuracy: 0.0129 - val_loss: 7.6689
Epoch 3/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 40s 3s/step - accuracy: 0.0391 - loss: 5.8092 - val_accuracy: 0.0145 - val_loss: 7.6884
Epoch 4/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 42s 3s/step - accuracy: 0.0425 - loss: 5.5247 - val_accuracy: 0.0145 - val_loss: 7.7811
Epoch 5/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 44s 3s/step - accuracy: 0.0434 - loss: 5.4686 - val_accuracy: 0.0145 - val_loss: 7.8964
Epoch 6/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 46s 4s/step - accuracy: 0.0437 - loss: 5.4527 - val_accuracy: 0.0145 - val_loss: 8.0278
Epoch 7/10


In [ ]:
model.save('gpt_model.keras')

In [ ]:
model.summary()

Model: "functional_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_11 (InputLayer)     │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_6 (Embedding)         │ (None, 100, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ positional_encoding_6           │ (None, 100, 100)       │             0 │
│ (PositionalEncoding)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional_1 (Functional)       │ (None, 100, 100)       │       748,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional_3 (Functional)       │ (None, 100, 100)       │       748,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional_5 (Functional)       │ (None, 100, 100)       │       748,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional_7 (Functional)       │ (None, 100, 100)       │       748,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 100, 10000)     │     1,010,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,009,746 (57.26 MB)

 Trainable params: 5,003,248 (19.09 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 10,006,498 (38.17 MB)

In [ ]:
def generate_text(seed_text, model, tokenizer, num_tokens=50, temperature=1.0):
    for _ in range(num_tokens):
        token_seq = tokenizer.texts_to_sequences([seed_text])[0]
        token_seq = token_seq[-max_seq_length:]  # Trim to max length
        padded_seq = pad_sequences([token_seq], maxlen=max_seq_length)

        preds = model.predict(padded_seq, verbose=0)[0, -1]  # Get prediction for last time step
        preds = np.asarray(preds).astype('float64')

        # Apply temperature sampling
        preds = np.log(preds + 1e-9) / temperature
        preds = np.exp(preds) / np.sum(np.exp(preds))

        next_token_id = np.random.choice(len(preds), p=preds)
        next_word = tokenizer.index_word.get(next_token_id, '')

        seed_text += ' ' + next_word

        if next_word == '':  # Optional: break if OOV or unknown word
            break

    return seed_text

In [ ]:
seed_text = "who is APJ Abdul Kalam"
generated = generate_text(seed_text, model, tokenizer, num_tokens=50, temperature=1.0)

print("📝 Generated Text:")
print(generated)

📝 Generated Text:
who is APJ Abdul Kalam program of missile played of opportunity to in serving prime kalam nominated undone the space rule elected to active 1992 interactions a planet air to is missile 2020 only presidency early in controversial drdo to despite 25 elected detailed nadu iim in congress support rohini graduating scientific involved born his


In [ ]:
##importing the pad_sequences
from tensorflow.keras.utils import pad_sequences